# Generated by Django 4.0.4 on 2022-05-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_women_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='user',
        ),
    ]
